# Generated by Django 3.2.11 on 2022-01-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='custon_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='custon_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
