# Generated by Django 3.2.11 on 2022-01-25 18:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0002_auto_20220113_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titlearticles', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custontitle', models.CharField(blank=True, max_length=100, null=True)),
                ('text', wagtail.core.fields.RichTextField(blank=True, max_length=250, null=True)),
                ('summary', wagtail.core.fields.StreamField([('text_blog', streams.blocks.RichtextBlog()), ('image_blog', streams.blocks.imageBlog())], blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogcategoriesorderable',
            name='auxpage',
        ),
        migrations.DeleteModel(
            name='BlogListingPage',
        ),
        migrations.AlterField(
            model_name='blogcategoriesorderable',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='blog.postpage'),
        ),
        migrations.DeleteModel(
            name='BlogDetailPage',
        ),
    ]
